import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import React from 'react';
import {useFetchye} from 'fetchye';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [word, setWord] = React.useState('');
  const {isLoading, data, error, run} = useFetchye('api/words');

  const addWord = React.useCallback(async () => {
    console.log('addWord ' + word);
    if (!data.body.includes(word.toLowerCase())) {
        await fetch('api/words', {
            method: 'POST',
            body: JSON.stringify({word})
        });
    } else {
        console.log('reject as duplicate ' + word);
    }
    setWord('')
    run();
  }, [word])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <input type="text" id='wordInput' value={word} onChange={(event) => setWord(event.target.value)}/>
          <button type="button" onClick={addWord}> Add Word </button>
          {isLoading && (
              <span>
                    Loading Words
              </span>
          )}
          {!isLoading && (
              <span>
                  <p>Words: ({data.body.length})</p>
                  { data.body.map(item => <p key={item}>{item}</p>) }

              </span>
          )}
      </main>
    </>
  )
}
